// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Source of truth: functions/config_schema.json
// Regenerate:       node scripts/gen_config_schema.js
//
// Any change to a setting's default, bounds, or metadata belongs in
// functions/config_schema.json, never in this file directly — a hand-edit here will be
// silently overwritten by the next regeneration. Neither this repo's CI nor
// cookrange-admin's checks this automatically today; cookrange-admin has a
// local, manually-run freshness check (`npm run verify:config-schema`) --
// see that repo's e2e/README.md for why it isn't wired into CI yet.

library;

/// Dotted-key defaults for every admin-editable setting, keyed exactly as
/// they appear in `functions/config_schema.json` and in the `app_config/*`
/// Firestore documents. `const` so a cold start has correct values (incl.
/// every feature kill-switch) with zero I/O — see DECISIONS.md ADR-023.
const Map<String, dynamic> kConfigDefaults = {
  'ai.allowed_models': <String>['openrouter/free', 'meta-llama/llama-3.2-11b-vision-instruct:free'],
  'ai.free_daily_limit': 2,
  'ai.max_messages': 30,
  'ai.max_retries': 3,
  'ai.max_tokens': 8192,
  'ai.max_tokens_by_type': <String, int>{},
  'ai.max_total_chars': 24000,
  'ai.model_by_type': <String, dynamic>{},
  'ai.model_pricing': <String, dynamic>{'google/gemini-2.0-flash-001': <String, dynamic>{'in': 0.1, 'out': 0.4}, 'openai/gpt-4o-mini': <String, dynamic>{'in': 0.15, 'out': 0.6}, 'openai/gpt-4o': <String, dynamic>{'in': 2.5, 'out': 10}},
  'ai.premium_daily_limit': 20,
  'ai.rate_max_in_window': 12,
  'ai.rate_window_ms': 60000,
  'ai.retry_delay_s': 2,
  'ai.temperature': 0.7,
  'ai.text_model': '',
  'ai.timeout_s': 90,
  'ai.vision_model': '',
  'announcement.cta_url': '',
  'announcement.dismissible': true,
  'announcement.enabled': false,
  'announcement.id': '',
  'announcement.message': <String, dynamic>{},
  'announcement.type': 'info',
  'client.check_in_radius_m': 100,
  'client.max_dishes_per_prompt': 180,
  'client.min_age_years': 16,
  'client.referral_pending_code_ttl_days': 7,
  'client.weekly_meal_plan_expiry_days': 7,
  'cost.pricing': <String, dynamic>{'firestoreReadPer100k': 0.06, 'firestoreWritePer100k': 0.18, 'firestoreDeletePer100k': 0.02, 'firestoreStoragePerGiBMonth': 0.18, 'firestoreFreeStorageGiB': 1, 'firestoreFreeReadsPerDay': 50000, 'firestoreFreeWritesPerDay': 20000, 'storagePerGBMonth': 0.026, 'storageDownloadPerGB': 0.12, 'storageFreeGB': 5, 'functionsInvocationPerMillion': 0.4, 'functionsFreeInvocationsPerMonth': 2000000, 'visionPer1000': 1.5, 'visionFreePerMonth': 1000, 'openRouterCostPerCallUsd': 0, 'openRouterCostPerVisionCallUsd': 0, 'premiumMonthlyPrice': 4.99, 'premiumYearlyPricePerMonth': 3.33, 'aiCreditsPackPrice': 1.99, 'storeCutFraction': 0.15},
  'economy.gym_commission_try': <String, double>{'com.cookrange.premium.monthly': 15.0, 'com.cookrange.premium.yearly': 120.0},
  'economy.referral_commission_try': 5.0,
  'economy.referral_max_uses': 10,
  'economy.referral_reward_days': 7,
  'economy.streak_freeze_grant_amount': 1,
  'endpoints.ai_proxy_url': '',
  'engagement.contrib_leaderboard_groups_per_run': 300,
  'engagement.contrib_leaderboard_top_n': 10,
  'engagement.credit_table': <String, dynamic>{'post_reactions': <String, dynamic>{'credit': 1, 'dailyCap': 2, 'threshold': 10}, 'comment_likes': <String, dynamic>{'credit': 1, 'dailyCap': 1, 'threshold': 5}, 'template_used': <String, dynamic>{'credit': 1, 'dailyCap': 3}, 'weekly_group_top3': <String, dynamic>{'credit': 5, 'weeklyCap': 1}},
  'engagement.weekly_candidate_buffer': 10,
  'engagement.weekly_contrib_groups_per_run': 300,
  'engagement.weekly_min_active_members': 3,
  'engagement.weekly_top_n': 3,
  'features.chat': true,
  'features.coach': true,
  'features.community': true,
  'features.fitness_twin': true,
  'features.food_scan': true,
  'features.gym': true,
  'features.gym_attribution': true,
  'features.gym_invite_codes': true,
  'features.marketplace': true,
  'features.meal_plan_templates': true,
  'features.nutrition_analytics': true,
  'features.photo_analysis': true,
  'features.programs': true,
  'features.referral': true,
  'features.squad': true,
  'features.voice_assistant': true,
  'features.weekly_recap': true,
  'gamification.achievement_points': <String, int>{'firstMealLogged': 10, 'firstPhotoLog': 15, 'firstPost': 10, 'firstCook': 20, 'streak7': 30, 'streak30': 75, 'streak100': 200, 'tierActive': 20, 'tierContributor': 50, 'tierExpert': 100, 'tierLegend': 250, 'level50': 300, 'groupTop3': 40, 'groupStreak4': 120, 'gymRegular': 60},
  'gamification.group_streak_achievement_threshold': 4,
  'gamification.gym_regular_checkin_threshold': 15,
  'gamification.level_curve_coefficient': 50,
  'gamification.local_utc_offset_hours': 3,
  'gamification.max_level': 999,
  'gamification.max_xp_events_per_call': 10,
  'gamification.tier_level_floor': <String, int>{'newcomer': 1, 'active': 5, 'contributor': 10, 'expert': 20, 'legend': 35},
  'gamification.xp_table': <String, dynamic>{'meal_logged': <String, dynamic>{'points': 5, 'dailyCap': 4}, 'streak_day': <String, dynamic>{'points': 10, 'dailyCap': 1}, 'check_in': <String, dynamic>{'points': 15, 'dailyCap': 1}, 'post_created': <String, dynamic>{'points': 20, 'dailyCap': 2}, 'comment_created': <String, dynamic>{'points': 5, 'dailyCap': 10}, 'reaction_given': <String, dynamic>{'points': 1, 'dailyCap': 20}, 'recipe_cooked': <String, dynamic>{'points': 25, 'dailyCap': 2}, 'template_accepted': <String, dynamic>{'points': 30, 'dailyCap': null}},
  'groups.activity_comments_scan_limit': 500,
  'groups.activity_groups_per_run': 200,
  'groups.activity_half_life_hours': 6.0,
  'groups.activity_signal_limit': 300,
  'groups.activity_window_hours': 24,
  'maintenance.enabled': false,
  'maintenance.message': <String, dynamic>{},
  'media.vision_daily_cap': 1000,
  'moderation.action_rate_limit': <String, dynamic>{'windowMs': 600000, 'max': 15, 'lockMs': 900000},
  'moderation.appeal_rate_limit': <String, dynamic>{'windowMs': 3600000, 'max': 5, 'lockMs': 3600000},
  'moderation.auto_restrict_flag_threshold': 5,
  'moderation.checkin_rate_limit': <String, dynamic>{'windowMs': 3600000, 'max': 6, 'lockMs': 3600000},
  'moderation.comment_min_text_length': 10,
  'moderation.comment_rate_limit': <String, dynamic>{'windowMs': 600000, 'max': 30, 'lockMs': 900000},
  'moderation.concentration_distinct_max': 3,
  'moderation.concentration_downweight': 0.2,
  'moderation.concentration_window': 20,
  'moderation.duplicate_recent_window': 20,
  'moderation.duplicate_similarity_threshold': 0.85,
  'moderation.follow_rate_limit': <String, dynamic>{'windowMs': 600000, 'max': 50, 'lockMs': 900000},
  'moderation.group_create_rate_limit': <String, dynamic>{'windowMs': 3600000, 'max': 5, 'lockMs': 3600000},
  'moderation.message_min_text_length': 10,
  'moderation.message_rate_limit': <String, dynamic>{'windowMs': 60000, 'max': 30, 'lockMs': 300000},
  'moderation.min_account_age_ms': 259200000,
  'moderation.post_min_text_length': 20,
  'moderation.post_rate_limit': <String, dynamic>{'windowMs': 600000, 'max': 20, 'lockMs': 900000},
  'moderation.reaction_rate_limit': <String, dynamic>{'windowMs': 300000, 'max': 100, 'lockMs': 600000},
  'moderation.reciprocity_downweight': 0.2,
  'moderation.reciprocity_min_pair_sample': 4,
  'moderation.reciprocity_ratio_threshold': 0.5,
  'moderation.report_rate_limit': <String, dynamic>{'windowMs': 600000, 'max': 8, 'lockMs': 900000},
  'presence.max_friends_fanout': 300,
  'presence.notify_log_ttl_days': 2,
  'presence.presence_ttl_ms': 14400000,
  'presence.quiet_hours_end': 23,
  'presence.quiet_hours_start': 7,
  'presence.rate_limit_reentry_ms': 600000,
  'presence.stale_sweep_limit': 200,
  'presence.timestamp_skew_ms': 300000,
  'privacy.k_anonymity_threshold': 5,
  'purchases.products': <String, dynamic>{'com.cookrange.premium.monthly': <String, dynamic>{'kind': 'subscription', 'tier': 'premium', 'days': 31}, 'com.cookrange.premium.yearly': <String, dynamic>{'kind': 'subscription', 'tier': 'premium', 'days': 365}, 'cookrange_ai_credits_10': <String, dynamic>{'kind': 'consumable', 'bonusCredits': 10}},
  'rollout.coach': 100,
  'rollout.gym': 100,
  'rollout.programs': 100,
  'rollout.squad': 100,
  'summaries.gen_rate_max_in_window': 1,
  'summaries.gen_rate_window_ms': 86400000,
  'summaries.max_scope_members_scan': 500,
  'summaries.stale_sweep_limit': 300,
  'summaries.ttl_ms': 604800000,
  'templates.max_message_length': 500,
  'templates.max_recipients_per_call': 100,
  'templates.offer_ttl_days': 14,
  'version.android_store_url': '',
  'version.force_update': false,
  'version.ios_store_url': '',
  'version.latest_android': '0.0.0',
  'version.latest_ios': '0.0.0',
  'version.min_supported_android': '0.0.0',
  'version.min_supported_ios': '0.0.0',
  'version.update_message': <String, dynamic>{},
};
